name: Test Fuchsia FIDL
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  test-fuchsia-fidl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm install
      - name: Download Fuchsia sdk/fidl
        run: |
          git clone --filter=blob:none --no-checkout --depth 1 --sparse --branch main https://fuchsia.googlesource.com/fuchsia fuchsia-sdk-fidl
          git -C fuchsia-sdk-fidl sparse-checkout set sdk/fidl
          git -C fuchsia-sdk-fidl checkout
          echo "Fuchsia commit: $(git -C fuchsia-sdk-fidl rev-parse HEAD)"
      - name: Parse Fuchsia sdk/fidl
        run: |
          echo "Testing Fuchsia commit: $(git -C fuchsia-sdk-fidl rev-parse HEAD)"
          npx tree-sitter parse -q -s "fuchsia-sdk-fidl/sdk/fidl/**/*.fidl"
